### ISSUE TITLE
`Name or service not known` errors are not retried

### ISSUE THREAD

**Issue by rolando** [scrapinghub/python-hubstorage#47]
The `_hc_retry_on_exception` function only retries `ConnectionError` when the underlying exception is `BadStatusLine`. In this case, we got a `socket.gaierror('Name or service not known')`. See the full traceback below:

```
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
  File "sh_scrapy/crawl.py", line 127, in _run_usercode
    _run(args, settings)
  File "sh_scrapy/crawl.py", line 89, in _run
    _run_pkgscript(args)
  File "sh_scrapy/crawl.py", line 110, in _run_pkgscript
    d.run_script(scriptname, {'__name__': '__main__'})
  File "dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "scrapy/tmp/eggs-cJgpCT/__main__.egg/EGG-INFO/scripts/run-script.py", line 55, in <module>
    maybe_capture_errors(main, settings)(settings)
  File "usr/lib/python2.7/dist-packages/raven/base.py", line 681, in wrapper
    return func(*funcargs, **funckwargs)
  File "scrapy/tmp/eggs-cJgpCT/__main__.egg/EGG-INFO/scripts/run-script.py", line 50, in main
    target(**kwargs)
  File "ompostprocess/cli.py", line 192, in main
    spider_name = hs_job.metadata['spider']
  File "hubstorage/resourcetype.py", line 202, in __getitem__
    return self._data[key]
  File "hubstorage/resourcetype.py", line 178, in _data
    r = self.apiget()
  File "hubstorage/resourcetype.py", line 39, in apiget
    return self.apirequest(_path, method='GET', **kwargs)
  File "hubstorage/resourcetype.py" line 32, in apirequest
    return jldecode(self._iter_lines(_path, **kwargs))
  File "hubstorage/resourcetype.py", line 27, in _iter_lines
    r = self.client.request(**kwargs)
  File "hubstorage/client.py", line 100, in request
    return self.retrier.call(invoke_request)
  File "dist-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "dist-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "dist-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "hubstorage/client.py", line 92, in invoke_request
    r = self.session.request(**kwargs)
  File "usr/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "usr/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "usr/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)

```

**Comment by rolando** [comment]
Another exception candidate to be retried:

```
Traceback (most recent call last):
  File "/tmp/eggs-IKoTZB/__main__.egg/ompostprocess/cli.py", line 212, in main
    db = runner.run()
  File "/tmp/eggs-IKoTZB/__main__.egg/ompostprocess/core.py", line 202, in run
    db = pipe.run(self, db)
  File "/tmp/eggs-IKoTZB/__main__.egg/ompostprocess/pipelines/__init__.py", line 163, in run
    return self.process(db)
  File "/tmp/eggs-IKoTZB/__main__.egg/ompostprocess/pipelines/mongo.py", line 167, in process
    or not self.is_within_instock_thresholds()
  File "/tmp/eggs-IKoTZB/__main__.egg/ompostprocess/pipelines/mongo.py", line 327, in is_within_instock_thresholds
    last_stats = self.get_last_stats()
  File "/tmp/eggs-IKoTZB/__main__.egg/ompostprocess/pipelines/mongo.py", line 380, in get_last_stats
    return self.hs_statscol.get(_key=self.spider.name)['last_stats']
  File "/usr/lib/python2.7/dist-packages/hubstorage/collectionsrt.py", line 103, in get
    return self._collections.get(self.coltype, self.colname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/hubstorage/collectionsrt.py", line 12, in get
    r = self.apiget((_type, _name, _key), params=params)
  File "/usr/lib/python2.7/dist-packages/hubstorage/resourcetype.py", line 39, in apiget
    return self.apirequest(_path, method='GET', **kwargs)
  File "/usr/lib/python2.7/dist-packages/hubstorage/resourcetype.py", line 32, in apirequest
    return jldecode(self._iter_lines(_path, **kwargs))
  File "/usr/lib/python2.7/dist-packages/hubstorage/resourcetype.py", line 27, in _iter_lines
    r = self.client.request(**kwargs)
  File "/usr/lib/python2.7/dist-packages/hubstorage/client.py", line 100, in request
    return self.retrier.call(invoke_request)
  File "/usr/lib/python2.7/dist-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/usr/lib/python2.7/dist-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/lib/python2.7/dist-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/lib/python2.7/dist-packages/hubstorage/client.py", line 92, in invoke_request
    r = self.session.request(**kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
```

**Comment by rolando** [comment]
Other unhandled exception when reading metadata:
```
ConnectionError: ('Connection aborted.', error(110, 'Connection timed out'))
  File "sh_scrapy/crawl.py", line 127, in _run_usercode
    _run(args, settings)
  File "sh_scrapy/crawl.py", line 89, in _run
    _run_pkgscript(args)
  File "sh_scrapy/crawl.py", line 110, in _run_pkgscript
    d.run_script(scriptname, {'__name__': '__main__'})
  File "dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "scrapy/tmp/eggs-Ue3TjE/__main__.egg/EGG-INFO/scripts/run-script.py", line 55, in <module>
    maybe_capture_errors(main, settings)(settings)
  File "usr/lib/python2.7/dist-packages/raven/base.py", line 681, in wrapper
    return func(*funcargs, **funckwargs)
  File "scrapy/tmp/eggs-Ue3TjE/__main__.egg/EGG-INFO/scripts/run-script.py", line 50, in main
    target(**kwargs)
  File "ompostprocess/cli.py", line 192, in main
    spider_name = hs_job.metadata['spider']
  File "hubstorage/resourcetype.py", line 202, in __getitem__
    return self._data[key]
  File "hubstorage/resourcetype.py", line 178, in _data
    r = self.apiget()
  File "hubstorage/resourcetype.py", line 39, in apiget
    return self.apirequest(_path, method='GET', **kwargs)
  File "hubstorage/resourcetype.py", line 32, in apirequest
    return jldecode(self._iter_lines(_path, **kwargs))
  File "hubstorage/resourcetype.py", line 27, in _iter_lines
    r = self.client.request(**kwargs)
  File "hubstorage/client.py", line 100, in request
    return self.retrier.call(invoke_request)
  File "dist-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "dist-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "dist-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "hubstorage/client.py", line 92, in invoke_request
    r = self.session.request(**kwargs)
  File "usr/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "usr/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "usr/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
```
